task:

  name: Builds
  timeout_in: 120m
  container:
    image: ubuntu:latest
    cpu: 8
    memory: 32G
  
  env:
    CIRRUS_WORKING_DIR: "/tmp/ci"

  build_script:
    - apt update && apt install sudo && sudo apt update && sudo apt upgrade -y
    - apt update && apt install sudo -y
    - sudo apt update && sudo apt upgrade -y
    - wget https://github.com/coder/code-server/releases/download/v4.8.0/code-server-4.8.0-linux-amd64.tar.gz
    - tar -xf code-server-4.8.0-linux-amd64.tar.gz
    - cd code-server-4.8.0-linux-amd64/bin
    - export PASSWORD="123456"
    - ./code-server >> /dev/null &
    - ssh -tR 9001:localhost:8080 example.com sirtunnel.py code.example.com 9001
