task:

  name: Builds
  timeout_in: 120m
  container:
    image: rust:latest
    cpu: 8
    memory: 32G
  
  env:
    CIRRUS_WORKING_DIR: "/tmp/ci"

  build_script:
    - apt update && apt install sudo && sudo apt update && sudo apt upgrade -y
    - cargo install bore-cli
